import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadCanonicalGameData } from "@/lib/game-data-canonical";
import { gameOperationCatalog } from "@/game-data/operation-catalog";
import { evaluateGameRecipeCorpus } from "@/lib/game-recipe-validation";

/**
 * Projects the M13 recipe database into a Web-safe browse dataset
 * (`data/database-browse-entries.ts`). The app/components/data layers must not
 * import game-data modules (architecture guard test); this script runs in the
 * scripts layer and emits a plain data file with no game-data imports.
 */
const data = loadCanonicalGameData();
const audit = evaluateGameRecipeCorpus(data.recipes, {
  operations: gameOperationCatalog,
  ingredients: data.ingredients,
  rightsRegistry: data.rightsRegistry,
  now: new Date().toISOString().slice(0, 10),
});

interface BrowseEntry {
  slug: string;
  itemType: string;
  categories: string[];
  cuisine: string;
  contexts: string[];
  servings: number;
  kcalPerServing: number;
  portions: number;
  steps: number;
  sourceType: string;
  flavors: string[];
}

const entries: BrowseEntry[] = data.recipes.map((recipe) => {
  const db = recipe.database;
  const flavor = db?.flavor;
  const flavors: string[] = [];
  if (flavor) {
    for (const [taste, intensity] of Object.entries(flavor.tastes)) {
      if (intensity > 0) flavors.push(`${taste}${intensity}`);
    }
    for (const aroma of flavor.aromaIds ?? []) flavors.push(aroma);
    for (const texture of flavor.textureIds ?? []) flavors.push(texture);
    for (const character of flavor.characterIds ?? []) flavors.push(character);
  }
  return {
    slug: recipe.slug,
    itemType: recipe.itemType,
    categories: [...(db?.tags.categoryTags ?? [])],
    cuisine: db?.tags.cuisineIds?.[0] ?? "",
    contexts: [...(db?.tags.servingContextIds ?? [])],
    servings: recipe.servings,
    kcalPerServing: Math.round(recipe.nutritionProfile.perServing.calories),
    portions: recipe.ingredientPortions.length,
    steps: recipe.operationGraph.nodes.length,
    sourceType: db?.sourceType ?? "",
    flavors: flavors.slice(0, 5),
  };
});

const summary = {
  total: data.recipes.length,
  baking: entries.filter((entry) => entry.categories.includes("baking")).length,
  bartending: entries.filter((entry) => entry.categories.includes("bartending")).length,
  dessert: entries.filter((entry) => entry.categories.includes("dessert")).length,
  ingredients: data.ingredients.ingredients.length,
  conversions: data.ingredients.conversionRecords.length,
  issues: audit.issues.length,
  sources: Object.entries(
    entries.reduce<Record<string, number>>((acc, entry) => {
      acc[entry.sourceType] = (acc[entry.sourceType] ?? 0) + 1;
      return acc;
    }, {}),
  ).map(([sourceType, count]) => ({ sourceType, count })),
};

const content = `// AUTO-GENERATED by scripts/build-database-browse-data.ts — do not edit by hand.
// Web-safe projection of the M13 recipe database for the internal /database browser.

export interface DatabaseBrowseEntry {
  slug: string;
  itemType: string;
  categories: string[];
  cuisine: string;
  contexts: string[];
  servings: number;
  kcalPerServing: number;
  portions: number;
  steps: number;
  sourceType: string;
  flavors: string[];
}

export interface DatabaseBrowseSummary {
  total: number;
  baking: number;
  bartending: number;
  dessert: number;
  ingredients: number;
  conversions: number;
  issues: number;
  sources: Array<{ sourceType: string; count: number }>;
}

export const databaseBrowseSummary: DatabaseBrowseSummary = ${JSON.stringify(summary, null, 2)};

export const databaseBrowseEntries: DatabaseBrowseEntry[] = ${JSON.stringify(entries, null, 2)};
`;

const path = resolve(process.cwd(), "data/database-browse-entries.ts");
writeFileSync(path, content, "utf8");
process.stdout.write(`Projected ${entries.length} database browse entries (issues: ${audit.issues.length})\n`);
