import { writeRecipes, type DraftRecipe } from "./recipe-database-build";

/**
 * Batch B: 50 database recipes (17 baking, 17 bartending, 16 dessert) —
 * knowledge-base authored ai-assisted drafts reaching the 120-entry
 * milestone (issue #108).
 */
const options = {
  generatorVersion: "m13-database-batch-b-1",
  sourceNotes: "Knowledge-base authored draft for the recipe database batch B; not eligible for Web publication or game export without full independent review.",
  accessedAt: "2026-09-14",
  allowOverwrite: true, // batch B files are deterministic; regeneration overwrites its own output
};

const drafts: DraftRecipe[] = [
  // ================= BAKING (17) =================
  {
    slug: "new-york-cheesecake",
    itemType: "dessert", servings: 12, yieldAmount: 12, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["american"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal"],
    flavor: { tastes: { sweet: 3, sour: 1 }, aromaIds: ["toasty"], textureIds: ["creamy", "soft"], characterIds: ["comforting"] },
    portions: [
      { id: "cream-cheese", grams: 680, amount: 680, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "granulated-sugar", grams: 150, amount: 150, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "egg", grams: 150, amount: 3, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "heavy-cream", grams: 120, amount: 120, unit: "ml", conversionId: "heavy-cream:ml:weight-v1", role: "main", state: "liquid" },
      { id: "almond-flour", grams: 150, amount: 150, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "butter", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "lemon", grams: 10, amount: 10, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "mix", inputs: [4, 5], durationMs: 30000, params: { strength: 0.4 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "shape", inputs: [], durationMs: 30000 },
      { op: "bake", inputs: [], waitMs: 600000, params: { temperatureC: 180 }, targets: [{ dimension: "browning", minimum: 0.3, maximum: 0.5, unit: "normalized" }], equipment: "oven" },
      { op: "whisk", inputs: [0, 1, 2, 6], durationMs: 180000, params: { strength: 0.4 }, targets: [{ dimension: "structural-integrity", minimum: 0.6, unit: "normalized" }] },
      { op: "add", inputs: [3], durationMs: 20000, params: { quantityG: 120 } },
      { op: "mix", inputs: [], durationMs: 30000, params: { strength: 0.3 } },
      { op: "bake", inputs: [], waitMs: 3600000, params: { temperatureC: 160 }, targets: [{ dimension: "doneness", minimum: 0.85, maximum: 0.95, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "chill", inputs: [], waitMs: 14400000, params: { temperatureC: 4 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "carrot-cake",
    itemType: "dessert", servings: 12, yieldAmount: 12, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["american"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "afternoon-tea"],
    flavor: { tastes: { sweet: 3, spicy: 1 }, aromaIds: ["spiced", "fruity"], textureIds: ["soft", "chewy"], characterIds: ["comforting", "warming"] },
    portions: [
      { id: "usda-wheat-flour", grams: 250, amount: 250, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "granulated-sugar", grams: 180, amount: 180, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "usda-carrot", grams: 250, amount: 250, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "egg", grams: 150, amount: 3, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "usda-canola-oil", grams: 180, amount: 180, unit: "ml", conversionId: "usda-canola-oil:ml:weight-v1", role: "main", state: "liquid" },
      { id: "walnut", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "cinnamon", grams: 5, amount: 5, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "cream-cheese", grams: 200, amount: 200, unit: "g", conversionId: "si:g:v1", role: "main" },
    ],
    ops: [
      { op: "whisk", inputs: [1, 3, 4], durationMs: 120000, params: { strength: 0.5 } },
      { op: "add", inputs: [0, 6], durationMs: 20000, params: { quantityG: 255 } },
      { op: "grind", inputs: [2], durationMs: 60000, params: { cutSizeMm: 3, uniformity: 0.7 } },
      { op: "mix", inputs: [], durationMs: 60000, params: { strength: 0.4 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "fold", inputs: [5], durationMs: 30000, params: { strength: 0.25 } },
      { op: "bake", inputs: [], waitMs: 2400000, params: { temperatureC: 175 }, targets: [{ dimension: "doneness", minimum: 0.95, unit: "normalized" }, { dimension: "browning", minimum: 0.35, maximum: 0.6, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "chill", inputs: [], waitMs: 1800000, params: { temperatureC: 20 } },
      { op: "whisk", inputs: [7], durationMs: 120000, params: { strength: 0.6 } },
      { op: "assemble", inputs: [], durationMs: 60000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "lemon-tart",
    itemType: "dessert", servings: 8, yieldAmount: 8, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["french"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "afternoon-tea"],
    flavor: { tastes: { sweet: 3, sour: 3 }, aromaIds: ["citrusy"], textureIds: ["creamy", "crisp"], characterIds: ["refreshing", "light"] },
    portions: [
      { id: "wheat-flour", grams: 180, amount: 180, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "butter", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "powdered-sugar", grams: 50, amount: 50, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "lemon", grams: 120, amount: 120, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "egg", grams: 150, amount: 3, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "granulated-sugar", grams: 120, amount: 120, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "heavy-cream", grams: 100, amount: 100, unit: "ml", conversionId: "heavy-cream:ml:weight-v1", role: "main", state: "liquid" },
    ],
    ops: [
      { op: "mix", inputs: [0, 1, 2], durationMs: 60000, params: { strength: 0.4 }, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "rest", inputs: [], waitMs: 1800000 },
      { op: "shape", inputs: [], durationMs: 60000 },
      { op: "bake", inputs: [], waitMs: 900000, params: { temperatureC: 190 }, targets: [{ dimension: "browning", minimum: 0.3, maximum: 0.55, unit: "normalized" }], equipment: "oven" },
      { op: "whisk", inputs: [3, 4, 5, 6], durationMs: 60000, params: { strength: 0.4 } },
      { op: "set-heat", durationMs: 30000, params: { temperatureC: 75 }, heat: { kind: "qualitative", descriptorId: "low-simmer", sourceFactId: "" }, equipment: "saucepan" },
      { op: "stir", inputs: [], durationMs: 600000, params: { strength: 0.5 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "strain", inputs: [], durationMs: 10000 },
      { op: "assemble", inputs: [], durationMs: 30000 },
      { op: "bake", inputs: [], waitMs: 600000, params: { temperatureC: 160 }, targets: [{ dimension: "doneness", minimum: 0.85, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "chill", inputs: [], waitMs: 7200000, params: { temperatureC: 4 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "apple-pie",
    itemType: "dessert", servings: 8, yieldAmount: 8, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["american"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "social-gathering"],
    flavor: { tastes: { sweet: 3, sour: 1 }, aromaIds: ["fruity", "spiced", "toasty"], textureIds: ["soft", "crisp"], characterIds: ["comforting", "warming"] },
    portions: [
      { id: "wheat-flour", grams: 300, amount: 300, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "butter", grams: 200, amount: 200, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
      { id: "granulated-sugar", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "usda-apple", grams: 900, amount: 900, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "brown-sugar", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "cinnamon", grams: 4, amount: 4, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "lemon", grams: 15, amount: 15, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "mix", inputs: [0, 2], durationMs: 30000, params: { strength: 0.3 } },
      { op: "add", inputs: [1], durationMs: 30000, params: { quantityG: 200 } },
      { op: "fold", inputs: [], durationMs: 60000, params: { strength: 0.2 }, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "rest", inputs: [], waitMs: 3600000 },
      { op: "slice", inputs: [3], durationMs: 180000, params: { cutSizeMm: 5, uniformity: 0.8 } },
      { op: "season", inputs: [4, 5, 6], durationMs: 60000, params: { quantityG: 119 } },
      { op: "shape", inputs: [], durationMs: 120000, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "assemble", inputs: [], durationMs: 120000 },
      { op: "bake", inputs: [], waitMs: 3000000, params: { temperatureC: 200 }, targets: [{ dimension: "browning", minimum: 0.45, maximum: 0.7, unit: "normalized" }, { dimension: "doneness", minimum: 0.9, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "chocolate-sponge-cake",
    itemType: "dessert", servings: 10, yieldAmount: 10, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["french"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "afternoon-tea"],
    flavor: { tastes: { sweet: 3, bitter: 1 }, aromaIds: ["roasted", "toasty"], textureIds: ["soft", "silky"], characterIds: ["comforting", "light"] },
    portions: [
      { id: "egg", grams: 300, amount: 6, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "granulated-sugar", grams: 150, amount: 150, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "wheat-flour", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "usda-cocoa", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "butter", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "main" },
    ],
    ops: [
      { op: "whisk", inputs: [0, 1], durationMs: 600000, params: { strength: 0.7 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "add", inputs: [2, 3], durationMs: 20000, params: { quantityG: 130 } },
      { op: "fold", inputs: [4], durationMs: 60000, params: { strength: 0.25 }, targets: [{ dimension: "structural-integrity", minimum: 0.65, unit: "normalized" }] },
      { op: "shape", inputs: [], durationMs: 30000 },
      { op: "bake", inputs: [], waitMs: 1500000, params: { temperatureC: 170 }, targets: [{ dimension: "doneness", minimum: 0.95, unit: "normalized" }, { dimension: "browning", minimum: 0.4, maximum: 0.65, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "pound-cake",
    itemType: "dessert", servings: 10, yieldAmount: 10, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["british"], mealRoleIds: ["dessert"], servingContextIds: ["afternoon-tea", "after-meal"],
    flavor: { tastes: { sweet: 3 }, aromaIds: ["toasty"], textureIds: ["soft", "tender"], characterIds: ["comforting"] },
    portions: [
      { id: "butter", grams: 225, amount: 225, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "granulated-sugar", grams: 225, amount: 225, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "egg", grams: 200, amount: 4, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "wheat-flour", grams: 225, amount: 225, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "usda-vanilla", grams: 4, amount: 4, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "salt", grams: 2.3, amount: 2.3, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "mix", inputs: [0, 1], durationMs: 300000, params: { strength: 0.6 }, targets: [{ dimension: "wateriness", maximum: 0.2, unit: "normalized" }] },
      { op: "add", inputs: [2], durationMs: 120000, params: { quantityG: 200 } },
      { op: "mix", inputs: [3, 4, 5], durationMs: 60000, params: { strength: 0.3 }, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "shape", inputs: [], durationMs: 30000 },
      { op: "bake", inputs: [], waitMs: 3600000, params: { temperatureC: 170 }, targets: [{ dimension: "doneness", minimum: 0.95, unit: "normalized" }, { dimension: "browning", minimum: 0.45, maximum: 0.7, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "cream-puffs",
    itemType: "dessert", servings: 12, yieldAmount: 12, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["french"], mealRoleIds: ["dessert"], servingContextIds: ["afternoon-tea", "after-meal"],
    flavor: { tastes: { sweet: 2 }, aromaIds: ["toasty"], textureIds: ["crisp", "creamy"], characterIds: ["light", "comforting"] },
    portions: [
      { id: "drinking-water", grams: 250, amount: 250, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
      { id: "butter", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "salt", grams: 2, amount: 2, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "granulated-sugar", grams: 5, amount: 5, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "wheat-flour", grams: 150, amount: 150, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "egg", grams: 250, amount: 5, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "heavy-cream", grams: 300, amount: 300, unit: "ml", conversionId: "heavy-cream:ml:weight-v1", role: "main", state: "liquid" },
      { id: "powdered-sugar", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "set-heat", durationMs: 30000, params: { temperatureC: 100 }, heat: { kind: "qualitative", descriptorId: "rolling-boil", sourceFactId: "" }, equipment: "saucepan" },
      { op: "add", inputs: [0, 1, 2, 3], durationMs: 60000, params: { quantityG: 357 } },
      { op: "add", inputs: [4], durationMs: 30000, params: { quantityG: 150 }, targets: [{ dimension: "wateriness", maximum: 0.25, unit: "normalized" }] },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "add", inputs: [5], durationMs: 180000, params: { quantityG: 250 } },
      { op: "mix", inputs: [], durationMs: 60000, params: { strength: 0.5 }, targets: [{ dimension: "structural-integrity", minimum: 0.6, unit: "normalized" }] },
      { op: "shape", inputs: [], durationMs: 60000 },
      { op: "bake", inputs: [], waitMs: 1500000, params: { temperatureC: 200 }, targets: [{ dimension: "browning", minimum: 0.45, maximum: 0.7, unit: "normalized" }, { dimension: "doneness", minimum: 0.95, unit: "normalized" }], equipment: "oven" },
      { op: "whisk", inputs: [6, 7], durationMs: 180000, params: { strength: 0.65 } },
      { op: "assemble", inputs: [], durationMs: 120000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "bagels",
    itemType: "dish", servings: 8, yieldAmount: 8, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking"], cuisineIds: ["american"], mealRoleIds: ["staple"], servingContextIds: ["breakfast", "lunch"],
    flavor: { tastes: { salty: 2, sweet: 1 }, aromaIds: ["toasty"], textureIds: ["chewy", "crisp"], characterIds: ["comforting"] },
    portions: [
      { id: "wheat-flour", grams: 500, amount: 500, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "drinking-water", grams: 300, amount: 300, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
      { id: "granulated-sugar", grams: 20, amount: 20, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "salt", grams: 10, amount: 10, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "active-dry-yeast", grams: 5, amount: 5, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "mix", inputs: [0, 1, 2, 3, 4], durationMs: 600000, params: { strength: 0.6 }, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "rest", inputs: [], waitMs: 3600000 },
      { op: "shape", inputs: [], durationMs: 300000, targets: [{ dimension: "structural-integrity", minimum: 0.8, unit: "normalized" }] },
      { op: "rest", inputs: [], waitMs: 1200000 },
      { op: "boil", inputs: [], waitMs: 120000, params: { temperatureC: 100 }, targets: [{ dimension: "doneness", minimum: 0.4, maximum: 0.6, unit: "normalized" }], equipment: "heavy-pot" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "bake", inputs: [], waitMs: 1500000, params: { temperatureC: 220 }, targets: [{ dimension: "browning", minimum: 0.5, maximum: 0.75, unit: "normalized" }, { dimension: "doneness", minimum: 0.95, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "soft-dinner-rolls",
    itemType: "dish", servings: 12, yieldAmount: 12, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking"], cuisineIds: ["american"], mealRoleIds: ["staple", "side"], servingContextIds: ["dinner"],
    flavor: { tastes: { sweet: 1, salty: 1 }, aromaIds: ["toasty"], textureIds: ["soft", "tender"], characterIds: ["comforting", "light"] },
    portions: [
      { id: "wheat-flour", grams: 500, amount: 500, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "milk", grams: 240, amount: 240, unit: "ml", conversionId: "milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "butter", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "granulated-sugar", grams: 50, amount: 50, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "active-dry-yeast", grams: 7, amount: 7, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "salt", grams: 8, amount: 8, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "mix", inputs: [0, 1, 3, 4, 5], durationMs: 600000, params: { strength: 0.5 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "add", inputs: [2], durationMs: 30000, params: { quantityG: 60 } },
      { op: "rest", inputs: [], waitMs: 5400000 },
      { op: "shape", inputs: [], durationMs: 300000, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "rest", inputs: [], waitMs: 1800000 },
      { op: "bake", inputs: [], waitMs: 1200000, params: { temperatureC: 190 }, targets: [{ dimension: "browning", minimum: 0.4, maximum: 0.65, unit: "normalized" }, { dimension: "doneness", minimum: 0.95, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "zucchini-bread",
    itemType: "dessert", servings: 10, yieldAmount: 10, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["american"], mealRoleIds: ["dessert"], servingContextIds: ["afternoon-tea", "breakfast"],
    flavor: { tastes: { sweet: 2 }, aromaIds: ["spiced"], textureIds: ["soft", "chewy"], characterIds: ["comforting", "light"] },
    portions: [
      { id: "zucchini", grams: 300, amount: 300, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "wheat-flour", grams: 250, amount: 250, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "brown-sugar", grams: 150, amount: 150, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "usda-canola-oil", grams: 120, amount: 120, unit: "ml", conversionId: "usda-canola-oil:ml:weight-v1", role: "main", state: "liquid" },
      { id: "egg", grams: 100, amount: 2, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "cinnamon", grams: 4, amount: 4, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "usda-baking-powder", grams: 5, amount: 5, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "grind", inputs: [0], durationMs: 60000, params: { cutSizeMm: 5, uniformity: 0.7 } },
      { op: "whisk", inputs: [2, 3, 4], durationMs: 60000, params: { strength: 0.5 } },
      { op: "add", inputs: [1, 5, 6], durationMs: 20000, params: { quantityG: 259 } },
      { op: "mix", inputs: [], durationMs: 60000, params: { strength: 0.35 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "bake", inputs: [], waitMs: 3600000, params: { temperatureC: 175 }, targets: [{ dimension: "doneness", minimum: 0.95, unit: "normalized" }, { dimension: "browning", minimum: 0.4, maximum: 0.65, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "pumpkin-pie",
    itemType: "dessert", servings: 8, yieldAmount: 8, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["american"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal"],
    flavor: { tastes: { sweet: 3, spicy: 1 }, aromaIds: ["spiced"], textureIds: ["creamy", "soft"], characterIds: ["comforting", "warming"] },
    portions: [
      { id: "pumpkin-puree", grams: 425, amount: 425, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "evaporated-milk", grams: 360, amount: 360, unit: "ml", conversionId: "evaporated-milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "granulated-sugar", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "brown-sugar", grams: 50, amount: 50, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "egg", grams: 100, amount: 2, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "cinnamon", grams: 3, amount: 3, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "wheat-flour", grams: 150, amount: 150, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "butter", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main" },
    ],
    ops: [
      { op: "mix", inputs: [6, 7], durationMs: 30000, params: { strength: 0.35 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "shape", inputs: [], durationMs: 60000 },
      { op: "whisk", inputs: [0, 1, 2, 3, 4, 5], durationMs: 60000, params: { strength: 0.4 } },
      { op: "assemble", inputs: [], durationMs: 30000 },
      { op: "bake", inputs: [], waitMs: 3000000, params: { temperatureC: 200 }, targets: [{ dimension: "doneness", minimum: 0.9, maximum: 0.95, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "chill", inputs: [], waitMs: 7200000, params: { temperatureC: 4 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "pecan-pie",
    itemType: "dessert", servings: 8, yieldAmount: 8, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["american"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "social-gathering"],
    flavor: { tastes: { sweet: 4 }, aromaIds: ["toasty", "roasted"], textureIds: ["chewy", "crisp"], characterIds: ["comforting", "hearty"] },
    portions: [
      { id: "pecan", grams: 200, amount: 200, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "brown-sugar", grams: 150, amount: 150, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "granulated-sugar", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "butter", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "egg", grams: 100, amount: 2, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "usda-vanilla", grams: 4, amount: 4, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "wheat-flour", grams: 150, amount: 150, unit: "g", conversionId: "si:g:v1", role: "main" },
    ],
    ops: [
      { op: "mix", inputs: [6, 3], durationMs: 60000, params: { strength: 0.35 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "shape", inputs: [], durationMs: 60000 },
      { op: "set-heat", durationMs: 30000, params: { temperatureC: 70 }, heat: { kind: "qualitative", descriptorId: "low-melt", sourceFactId: "" }, equipment: "saucepan" },
      { op: "add", inputs: [1, 2, 3], durationMs: 60000, params: { quantityG: 310 } },
      { op: "whisk", inputs: [4, 5], durationMs: 60000, params: { strength: 0.4 } },
      { op: "mix", inputs: [0], durationMs: 30000, params: { strength: 0.3 } },
      { op: "assemble", inputs: [], durationMs: 30000 },
      { op: "bake", inputs: [], waitMs: 3000000, params: { temperatureC: 180 }, targets: [{ dimension: "doneness", minimum: 0.9, unit: "normalized" }, { dimension: "browning", minimum: 0.45, maximum: 0.7, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "blueberry-muffins",
    itemType: "dessert", servings: 12, yieldAmount: 12, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["american"], mealRoleIds: ["dessert"], servingContextIds: ["breakfast", "afternoon-tea"],
    flavor: { tastes: { sweet: 2, sour: 1 }, aromaIds: ["fruity"], textureIds: ["soft", "juicy"], characterIds: ["comforting", "light"] },
    portions: [
      { id: "wheat-flour", grams: 250, amount: 250, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "granulated-sugar", grams: 120, amount: 120, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "usda-blueberry", grams: 200, amount: 200, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "milk", grams: 120, amount: 120, unit: "ml", conversionId: "milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "egg", grams: 50, amount: 1, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "butter", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "usda-baking-powder", grams: 10, amount: 10, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "salt", grams: 1.2, amount: 1.2, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "mix", inputs: [0, 1, 6, 7], durationMs: 30000, params: { strength: 0.3 } },
      { op: "whisk", inputs: [3, 4, 5], durationMs: 60000, params: { strength: 0.5 } },
      { op: "mix", inputs: [], durationMs: 30000, params: { strength: 0.35 }, targets: [{ dimension: "structural-integrity", minimum: 0.65, unit: "normalized" }] },
      { op: "fold", inputs: [2], durationMs: 30000, params: { strength: 0.2 } },
      { op: "shape", inputs: [], durationMs: 60000 },
      { op: "bake", inputs: [], waitMs: 1320000, params: { temperatureC: 200 }, targets: [{ dimension: "doneness", minimum: 0.95, unit: "normalized" }, { dimension: "browning", minimum: 0.35, maximum: 0.6, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "oatmeal-cookies",
    itemType: "dessert", servings: 24, yieldAmount: 24, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["american"], mealRoleIds: ["dessert"], servingContextIds: ["afternoon-tea", "social-gathering"],
    flavor: { tastes: { sweet: 3 }, aromaIds: ["toasty", "fruity"], textureIds: ["chewy", "crisp"], characterIds: ["comforting"] },
    portions: [
      { id: "usda-oats", grams: 300, amount: 300, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "butter", grams: 200, amount: 200, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "brown-sugar", grams: 180, amount: 180, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "egg", grams: 100, amount: 2, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "raisin", grams: 150, amount: 150, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "wheat-flour", grams: 150, amount: 150, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "cinnamon", grams: 4, amount: 4, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "salt", grams: 2.3, amount: 2.3, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "mix", inputs: [1, 2], durationMs: 180000, params: { strength: 0.5 } },
      { op: "add", inputs: [3], durationMs: 60000, params: { quantityG: 100 } },
      { op: "mix", inputs: [0, 5, 6, 7], durationMs: 60000, params: { strength: 0.4 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "fold", inputs: [4], durationMs: 30000, params: { strength: 0.2 } },
      { op: "shape", inputs: [], durationMs: 120000 },
      { op: "bake", inputs: [], waitMs: 720000, params: { temperatureC: 180 }, targets: [{ dimension: "browning", minimum: 0.45, maximum: 0.7, unit: "normalized" }, { dimension: "doneness", minimum: 0.9, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "macarons",
    itemType: "dessert", servings: 20, yieldAmount: 20, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["french"], mealRoleIds: ["dessert"], servingContextIds: ["afternoon-tea", "after-meal"],
    flavor: { tastes: { sweet: 4 }, textureIds: ["crisp", "chewy"], characterIds: ["light", "comforting"] },
    portions: [
      { id: "almond-flour", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "powdered-sugar", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "egg", grams: 90, amount: 90, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
      { id: "granulated-sugar", grams: 75, amount: 75, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "cream-of-tartar", grams: 2, amount: 2, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "dark-chocolate", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "heavy-cream", grams: 60, amount: 60, unit: "ml", conversionId: "heavy-cream:ml:weight-v1", role: "main", state: "liquid" },
    ],
    ops: [
      { op: "mix", inputs: [0, 1], durationMs: 30000, params: { strength: 0.3 } },
      { op: "whisk", inputs: [2, 3, 4], durationMs: 300000, params: { strength: 0.7 }, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "fold", inputs: [], durationMs: 60000, params: { strength: 0.25 } },
      { op: "shape", inputs: [], durationMs: 180000, targets: [{ dimension: "structural-integrity", minimum: 0.8, unit: "normalized" }] },
      { op: "rest", inputs: [], waitMs: 1800000 },
      { op: "bake", inputs: [], waitMs: 900000, params: { temperatureC: 150 }, targets: [{ dimension: "doneness", minimum: 0.9, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "set-heat", durationMs: 30000, params: { temperatureC: 50 }, heat: { kind: "qualitative", descriptorId: "low-melt", sourceFactId: "" }, equipment: "saucepan" },
      { op: "add", inputs: [5, 6], durationMs: 120000, params: { quantityG: 160 } },
      { op: "chill", inputs: [], waitMs: 1800000, params: { temperatureC: 20 } },
      { op: "assemble", inputs: [], durationMs: 300000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "almond-biscotti",
    itemType: "dessert", servings: 30, yieldAmount: 30, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["italian"], mealRoleIds: ["dessert"], servingContextIds: ["afternoon-tea", "social-gathering"],
    flavor: { tastes: { sweet: 2, bitter: 1 }, aromaIds: ["roasted", "toasty"], textureIds: ["crisp", "chewy"], characterIds: ["comforting", "light"] },
    portions: [
      { id: "wheat-flour", grams: 300, amount: 300, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "almond-flour", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "granulated-sugar", grams: 200, amount: 200, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "egg", grams: 150, amount: 3, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "butter", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "usda-baking-powder", grams: 8, amount: 8, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "walnut", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main" },
    ],
    ops: [
      { op: "whisk", inputs: [2, 3], durationMs: 120000, params: { strength: 0.5 } },
      { op: "add", inputs: [0, 1, 4, 5], durationMs: 30000, params: { quantityG: 468 } },
      { op: "mix", inputs: [], durationMs: 60000, params: { strength: 0.4 }, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "fold", inputs: [6], durationMs: 30000, params: { strength: 0.2 } },
      { op: "shape", inputs: [], durationMs: 120000, targets: [{ dimension: "structural-integrity", minimum: 0.8, unit: "normalized" }] },
      { op: "bake", inputs: [], waitMs: 1500000, params: { temperatureC: 170 }, targets: [{ dimension: "doneness", minimum: 0.8, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "rest", inputs: [], waitMs: 600000 },
      { op: "slice", inputs: [], durationMs: 60000, params: { cutSizeMm: 10, uniformity: 0.85 } },
      { op: "bake", inputs: [], waitMs: 1200000, params: { temperatureC: 150 }, targets: [{ dimension: "browning", minimum: 0.5, maximum: 0.75, unit: "normalized" }, { dimension: "doneness", minimum: 0.95, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "chocolate-souffle",
    itemType: "dessert", servings: 4, yieldAmount: 4, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["baking", "dessert"], cuisineIds: ["french"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal"],
    flavor: { tastes: { sweet: 3, bitter: 2 }, aromaIds: ["roasted"], textureIds: ["silky", "soft"], characterIds: ["light", "comforting"] },
    portions: [
      { id: "dark-chocolate", grams: 130, amount: 130, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "butter", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "egg", grams: 120, amount: 120, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
      { id: "granulated-sugar", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "heavy-cream", grams: 100, amount: 100, unit: "ml", conversionId: "heavy-cream:ml:weight-v1", role: "main", state: "liquid" },
    ],
    ops: [
      { op: "set-heat", durationMs: 30000, params: { temperatureC: 55 }, heat: { kind: "qualitative", descriptorId: "low-melt", sourceFactId: "" }, equipment: "saucepan" },
      { op: "add", inputs: [0, 1], durationMs: 180000, params: { quantityG: 170 } },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "mix", inputs: [2], durationMs: 30000, params: { strength: 0.4 } },
      { op: "whisk", inputs: [2, 3], durationMs: 300000, params: { strength: 0.75 }, targets: [{ dimension: "structural-integrity", minimum: 0.8, unit: "normalized" }] },
      { op: "fold", inputs: [], durationMs: 60000, params: { strength: 0.3 } },
      { op: "shape", inputs: [], durationMs: 30000, targets: [{ dimension: "structural-integrity", minimum: 0.85, unit: "normalized" }] },
      { op: "bake", inputs: [], waitMs: 900000, params: { temperatureC: 190 }, targets: [{ dimension: "doneness", minimum: 0.8, maximum: 0.9, unit: "normalized" }, { dimension: "browning", minimum: 0.25, maximum: 0.5, unit: "normalized" }], equipment: "oven" },
      { op: "remove", inputs: [], durationMs: 3000 },
      { op: "serve", inputs: [4], durationMs: 5000 },
    ],
  },
];

// ================= BARTENDING (17) =================
drafts.push(
  {
    slug: "aperol-spritz",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 180, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["italian"], mealRoleIds: ["drink"], servingContextIds: ["aperitif", "social-gathering"],
    flavor: { tastes: { bitter: 2, sweet: 2 }, aromaIds: ["citrusy", "herbal"], characterIds: ["refreshing", "appetizing"] },
    portions: [
      { id: "aperol", grams: 42.4, amount: 40, unit: "ml", conversionId: "aperol:ml:weight-v1", role: "main", state: "liquid" },
      { id: "prosecco", grams: 59.4, amount: 60, unit: "ml", conversionId: "prosecco:ml:weight-v1", role: "main", state: "liquid" },
      { id: "club-soda", grams: 60, amount: 60, unit: "ml", conversionId: "club-soda:ml:weight-v1", role: "main", state: "liquid" },
      { id: "usda-orange", grams: 8, amount: 8, unit: "g", conversionId: "si:g:v1", role: "garnish" },
      { id: "ice", grams: 70, amount: 70, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [4], durationMs: 5000, params: { quantityG: 70 } },
      { op: "add", inputs: [0], durationMs: 5000, params: { quantityG: 42 } },
      { op: "add", inputs: [1], durationMs: 5000, params: { quantityG: 59 } },
      { op: "add", inputs: [2], durationMs: 5000, params: { quantityG: 60 } },
      { op: "stir", inputs: [], durationMs: 10000, params: { strength: 0.4 }, targets: [{ dimension: "structural-integrity", minimum: 0.5, unit: "normalized" }] },
      { op: "garnish", inputs: [3], durationMs: 8000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "french-75",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 150, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["french"], mealRoleIds: ["drink"], servingContextIds: ["aperitif", "social-gathering"],
    flavor: { tastes: { sour: 2, sweet: 2, bitter: 1 }, aromaIds: ["citrusy"], textureIds: ["crisp"], characterIds: ["refreshing", "light"] },
    portions: [
      { id: "gin-80", grams: 23.75, amount: 25, unit: "ml", conversionId: "gin-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "lemon", grams: 15, amount: 15, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "simple-syrup", grams: 15, amount: 15, unit: "g", conversionId: "si:g:v1", role: "seasoning", state: "liquid" },
      { id: "prosecco", grams: 89.1, amount: 90, unit: "ml", conversionId: "prosecco:ml:weight-v1", role: "main", state: "liquid" },
      { id: "ice", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [0, 1, 2], durationMs: 10000, params: { quantityG: 54 } },
      { op: "add", inputs: [4], durationMs: 5000, params: { quantityG: 80 } },
      { op: "mix", inputs: [], durationMs: 15000, params: { strength: 0.85 } },
      { op: "strain", inputs: [], durationMs: 10000 },
      { op: "add", inputs: [3], durationMs: 8000, params: { quantityG: 89 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "whiskey-sour",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 120, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["american"], mealRoleIds: ["drink"], servingContextIds: ["after-meal", "social-gathering"],
    flavor: { tastes: { sour: 3, sweet: 2 }, aromaIds: ["roasted"], textureIds: ["silky"], characterIds: ["appetizing", "warming"] },
    portions: [
      { id: "bourbon-80", grams: 47, amount: 50, unit: "ml", conversionId: "bourbon-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "lemon", grams: 25, amount: 25, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "simple-syrup", grams: 20, amount: 20, unit: "g", conversionId: "si:g:v1", role: "seasoning", state: "liquid" },
      { id: "egg", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared", optional: true },
      { id: "ice", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [0, 1, 2, 3], durationMs: 10000, params: { quantityG: 122 } },
      { op: "add", inputs: [4], durationMs: 5000, params: { quantityG: 80 } },
      { op: "mix", inputs: [], durationMs: 15000, params: { strength: 0.9 }, targets: [{ dimension: "structural-integrity", minimum: 0.6, unit: "normalized" }] },
      { op: "strain", inputs: [], durationMs: 10000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "old-fashioned",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 90, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["american"], mealRoleIds: ["drink"], servingContextIds: ["after-meal"],
    flavor: { tastes: { sweet: 1, bitter: 2 }, aromaIds: ["roasted", "spiced"], characterIds: ["warming", "comforting"] },
    portions: [
      { id: "bourbon-80", grams: 56.4, amount: 60, unit: "ml", conversionId: "bourbon-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "simple-syrup", grams: 8, amount: 8, unit: "g", conversionId: "si:g:v1", role: "seasoning", state: "liquid" },
      { id: "orange-bitters", grams: 1, amount: 1, unit: "g", conversionId: "si:g:v1", role: "seasoning", state: "liquid" },
      { id: "usda-orange", grams: 10, amount: 10, unit: "g", conversionId: "si:g:v1", role: "garnish" },
      { id: "ice", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [1, 2], durationMs: 8000, params: { quantityG: 9 } },
      { op: "add", inputs: [4], durationMs: 5000, params: { quantityG: 60 } },
      { op: "add", inputs: [0], durationMs: 8000, params: { quantityG: 56 } },
      { op: "stir", inputs: [], durationMs: 20000, params: { strength: 0.4 }, targets: [{ dimension: "structural-integrity", minimum: 0.5, unit: "normalized" }] },
      { op: "garnish", inputs: [3], durationMs: 8000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "manhattan",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 90, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["american"], mealRoleIds: ["drink"], servingContextIds: ["after-meal", "social-gathering"],
    flavor: { tastes: { sweet: 2, bitter: 2 }, aromaIds: ["roasted", "herbal"], characterIds: ["warming", "hearty"] },
    portions: [
      { id: "bourbon-80", grams: 47, amount: 50, unit: "ml", conversionId: "bourbon-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "sweet-vermouth", grams: 25.75, amount: 25, unit: "ml", conversionId: "sweet-vermouth:ml:weight-v1", role: "main", state: "liquid" },
      { id: "orange-bitters", grams: 1, amount: 1, unit: "g", conversionId: "si:g:v1", role: "seasoning", state: "liquid" },
      { id: "usda-orange", grams: 8, amount: 8, unit: "g", conversionId: "si:g:v1", role: "garnish" },
      { id: "ice", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [0, 1, 2], durationMs: 10000, params: { quantityG: 74 } },
      { op: "add", inputs: [4], durationMs: 5000, params: { quantityG: 60 } },
      { op: "stir", inputs: [], durationMs: 25000, params: { strength: 0.45 }, targets: [{ dimension: "structural-integrity", minimum: 0.55, unit: "normalized" }] },
      { op: "strain", inputs: [], durationMs: 10000 },
      { op: "garnish", inputs: [3], durationMs: 8000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "dry-martini",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 90, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["american"], mealRoleIds: ["drink"], servingContextIds: ["aperitif"],
    flavor: { tastes: { bitter: 2 }, aromaIds: ["herbal"], characterIds: ["clean-tasting", "appetizing"] },
    portions: [
      { id: "gin-80", grams: 61.75, amount: 65, unit: "ml", conversionId: "gin-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "dry-vermouth", grams: 10.2, amount: 10, unit: "ml", conversionId: "dry-vermouth:ml:weight-v1", role: "main", state: "liquid" },
      { id: "orange-bitters", grams: 0.5, amount: 0.5, unit: "g", conversionId: "si:g:v1", role: "seasoning", state: "liquid", optional: true },
      { id: "ice", grams: 70, amount: 70, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [0, 1, 2], durationMs: 8000, params: { quantityG: 72 } },
      { op: "add", inputs: [3], durationMs: 5000, params: { quantityG: 70 } },
      { op: "stir", inputs: [], durationMs: 30000, params: { strength: 0.5 }, targets: [{ dimension: "structural-integrity", minimum: 0.6, unit: "normalized" }] },
      { op: "strain", inputs: [], durationMs: 10000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "cosmopolitan",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 120, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["american"], mealRoleIds: ["drink"], servingContextIds: ["social-gathering", "aperitif"],
    flavor: { tastes: { sour: 3, sweet: 2, bitter: 1 }, aromaIds: ["citrusy"], characterIds: ["refreshing", "light"] },
    portions: [
      { id: "vodka-80", grams: 33.25, amount: 35, unit: "ml", conversionId: "vodka-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "orange-liqueur-80", grams: 10.3, amount: 10, unit: "ml", conversionId: "orange-liqueur-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "cranberry-juice", grams: 30, amount: 30, unit: "ml", conversionId: "cranberry-juice:ml:weight-v1", role: "main", state: "liquid" },
      { id: "lime", grams: 15, amount: 15, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "ice", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [0, 1, 2, 3], durationMs: 10000, params: { quantityG: 89 } },
      { op: "add", inputs: [4], durationMs: 5000, params: { quantityG: 80 } },
      { op: "mix", inputs: [], durationMs: 15000, params: { strength: 0.85 } },
      { op: "strain", inputs: [], durationMs: 10000 },
      { op: "garnish", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "long-island-iced-tea",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 300, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["american"], mealRoleIds: ["drink"], servingContextIds: ["social-gathering"],
    flavor: { tastes: { sour: 2, sweet: 2, bitter: 2 }, textureIds: ["crisp"], characterIds: ["refreshing", "hearty"] },
    portions: [
      { id: "vodka-80", grams: 14.25, amount: 15, unit: "ml", conversionId: "vodka-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "gin-80", grams: 14.25, amount: 15, unit: "ml", conversionId: "gin-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "white-rum-80", grams: 14.25, amount: 15, unit: "ml", conversionId: "white-rum-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "tequila-blanco-80", grams: 14.25, amount: 15, unit: "ml", conversionId: "tequila-blanco-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "orange-liqueur-80", grams: 15.45, amount: 15, unit: "ml", conversionId: "orange-liqueur-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "lemon", grams: 20, amount: 20, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "simple-syrup", grams: 20, amount: 20, unit: "g", conversionId: "si:g:v1", role: "seasoning", state: "liquid" },
      { id: "cola", grams: 100, amount: 100, unit: "ml", conversionId: "cola:ml:weight-v1", role: "main", state: "liquid" },
      { id: "ice", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [0, 1, 2, 3, 4], durationMs: 15000, params: { quantityG: 72 } },
      { op: "add", inputs: [5, 6], durationMs: 8000, params: { quantityG: 40 } },
      { op: "add", inputs: [8], durationMs: 5000, params: { quantityG: 100 } },
      { op: "mix", inputs: [], durationMs: 15000, params: { strength: 0.85 } },
      { op: "add", inputs: [7], durationMs: 8000, params: { quantityG: 100 } },
      { op: "stir", inputs: [], durationMs: 8000, params: { strength: 0.3 }, targets: [{ dimension: "structural-integrity", minimum: 0.4, unit: "normalized" }] },
      { op: "garnish", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "tequila-sunrise",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 250, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["mexican"], mealRoleIds: ["drink"], servingContextIds: ["social-gathering", "afternoon-tea"],
    flavor: { tastes: { sweet: 3, sour: 1 }, aromaIds: ["citrusy", "fruity"], textureIds: ["crisp"], characterIds: ["refreshing", "light"] },
    portions: [
      { id: "tequila-blanco-80", grams: 42.75, amount: 45, unit: "ml", conversionId: "tequila-blanco-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "orange-juice", grams: 135, amount: 135, unit: "ml", conversionId: "orange-juice:ml:weight-v1", role: "main", state: "liquid" },
      { id: "grenadine-syrup", grams: 20, amount: 20, unit: "g", conversionId: "si:g:v1", role: "seasoning", state: "liquid" },
      { id: "ice", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [3], durationMs: 5000, params: { quantityG: 80 } },
      { op: "add", inputs: [0], durationMs: 5000, params: { quantityG: 43 } },
      { op: "add", inputs: [1], durationMs: 8000, params: { quantityG: 135 } },
      { op: "stir", inputs: [], durationMs: 8000, params: { strength: 0.3 } },
      { op: "add", inputs: [2], durationMs: 10000, params: { quantityG: 20 }, targets: [{ dimension: "structural-integrity", minimum: 0.4, unit: "normalized" }] },
      { op: "garnish", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "paloma",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 250, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["mexican"], mealRoleIds: ["drink"], servingContextIds: ["social-gathering", "aperitif"],
    flavor: { tastes: { sour: 2, sweet: 1, bitter: 1 }, aromaIds: ["citrusy"], textureIds: ["crisp"], characterIds: ["refreshing", "light"] },
    portions: [
      { id: "tequila-blanco-80", grams: 42.75, amount: 45, unit: "ml", conversionId: "tequila-blanco-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "lime", grams: 22.5, amount: 22.5, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "club-soda", grams: 150, amount: 150, unit: "ml", conversionId: "club-soda:ml:weight-v1", role: "main", state: "liquid" },
      { id: "salt", grams: 2, amount: 2, unit: "g", conversionId: "si:g:v1", role: "garnish" },
      { id: "ice", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [4], durationMs: 5000, params: { quantityG: 80 } },
      { op: "add", inputs: [0, 1], durationMs: 8000, params: { quantityG: 65 } },
      { op: "add", inputs: [2], durationMs: 8000, params: { quantityG: 150 } },
      { op: "stir", inputs: [], durationMs: 10000, params: { strength: 0.35 }, targets: [{ dimension: "structural-integrity", minimum: 0.45, unit: "normalized" }] },
      { op: "garnish", inputs: [3], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "mint-julep",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 150, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["american"], mealRoleIds: ["drink"], servingContextIds: ["social-gathering", "after-meal"],
    flavor: { tastes: { sweet: 2 }, aromaIds: ["herbal"], textureIds: ["crisp"], characterIds: ["refreshing", "warming"] },
    portions: [
      { id: "bourbon-80", grams: 56.4, amount: 60, unit: "ml", conversionId: "bourbon-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "fresh-mint", grams: 8, amount: 8, unit: "g", conversionId: "si:g:v1", role: "garnish" },
      { id: "simple-syrup", grams: 15, amount: 15, unit: "g", conversionId: "si:g:v1", role: "seasoning", state: "liquid" },
      { id: "ice", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "crush", inputs: [1, 2], durationMs: 15000, params: { strength: 0.5 }, targets: [{ dimension: "structural-integrity", maximum: 0.2, unit: "normalized" }] },
      { op: "add", inputs: [3], durationMs: 8000, params: { quantityG: 100 } },
      { op: "add", inputs: [0], durationMs: 8000, params: { quantityG: 56 } },
      { op: "stir", inputs: [], durationMs: 20000, params: { strength: 0.5 }, targets: [{ dimension: "structural-integrity", minimum: 0.5, unit: "normalized" }] },
      { op: "garnish", inputs: [1], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "gin-and-tonic",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 250, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["british"], mealRoleIds: ["drink"], servingContextIds: ["aperitif", "social-gathering"],
    flavor: { tastes: { bitter: 2, sweet: 1 }, aromaIds: ["herbal", "citrusy"], textureIds: ["crisp"], characterIds: ["refreshing", "clean-tasting"] },
    portions: [
      { id: "gin-80", grams: 47.5, amount: 50, unit: "ml", conversionId: "gin-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "club-soda", grams: 150, amount: 150, unit: "ml", conversionId: "club-soda:ml:weight-v1", role: "main", state: "liquid" },
      { id: "lime", grams: 10, amount: 10, unit: "g", conversionId: "si:g:v1", role: "garnish" },
      { id: "ice", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [3], durationMs: 5000, params: { quantityG: 80 } },
      { op: "add", inputs: [0], durationMs: 5000, params: { quantityG: 48 } },
      { op: "add", inputs: [1], durationMs: 8000, params: { quantityG: 150 } },
      { op: "stir", inputs: [], durationMs: 10000, params: { strength: 0.35 }, targets: [{ dimension: "structural-integrity", minimum: 0.45, unit: "normalized" }] },
      { op: "garnish", inputs: [2], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "pina-colada",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 200, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["fusion"], mealRoleIds: ["drink"], servingContextIds: ["social-gathering", "after-meal"],
    flavor: { tastes: { sweet: 3 }, aromaIds: ["fruity", "floral"], textureIds: ["creamy", "silky"], characterIds: ["refreshing", "comforting"] },
    portions: [
      { id: "white-rum-80", grams: 42.75, amount: 45, unit: "ml", conversionId: "white-rum-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "coconut-milk", grams: 90, amount: 90, unit: "ml", conversionId: "coconut-milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "pineapple-juice", grams: 90, amount: 90, unit: "ml", conversionId: "pineapple-juice:ml:weight-v1", role: "main", state: "liquid" },
      { id: "lime", grams: 7.5, amount: 7.5, unit: "g", conversionId: "si:g:v1", role: "garnish" },
      { id: "ice", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [0, 1, 2, 4], durationMs: 10000, params: { quantityG: 302 } },
      { op: "blend", inputs: [], durationMs: 30000, params: { strength: 0.8 }, targets: [{ dimension: "structural-integrity", maximum: 0.2, unit: "normalized" }] },
      { op: "strain", inputs: [], durationMs: 10000 },
      { op: "garnish", inputs: [3], durationMs: 8000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "irish-coffee",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 240, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["british"], mealRoleIds: ["drink"], servingContextIds: ["after-meal"],
    flavor: { tastes: { sweet: 2, bitter: 2 }, aromaIds: ["roasted"], textureIds: ["creamy"], characterIds: ["warming", "comforting"] },
    portions: [
      { id: "irish-cream-34", grams: 47.25, amount: 45, unit: "ml", conversionId: "irish-cream-34:ml:weight-v1", role: "main", state: "liquid" },
      { id: "brewed-espresso", grams: 120, amount: 120, unit: "ml", conversionId: "brewed-espresso:ml:weight-v1", role: "main", state: "liquid" },
      { id: "brown-sugar", grams: 10, amount: 10, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "heavy-cream", grams: 40, amount: 40, unit: "ml", conversionId: "heavy-cream:ml:weight-v1", role: "main", state: "liquid" },
    ],
    ops: [
      { op: "set-heat", durationMs: 60000, params: { temperatureC: 95 }, heat: { kind: "qualitative", descriptorId: "brew-hot", sourceFactId: "" }, equipment: "kettle" },
      { op: "add", inputs: [1, 2], durationMs: 30000, params: { quantityG: 130 } },
      { op: "add", inputs: [0], durationMs: 10000, params: { quantityG: 47 } },
      { op: "stir", inputs: [], durationMs: 15000, params: { strength: 0.5 } },
      { op: "whisk", inputs: [3], durationMs: 60000, params: { strength: 0.5 } },
      { op: "add", inputs: [3], durationMs: 10000, params: { quantityG: 40 }, targets: [{ dimension: "structural-integrity", minimum: 0.4, unit: "normalized" }] },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "sidecar",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 100, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["french"], mealRoleIds: ["drink"], servingContextIds: ["after-meal", "aperitif"],
    flavor: { tastes: { sour: 2, sweet: 2, bitter: 1 }, aromaIds: ["citrusy"], characterIds: ["warming", "appetizing"] },
    portions: [
      { id: "brandy-80", grams: 47, amount: 50, unit: "ml", conversionId: "brandy-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "orange-liqueur-80", grams: 20.6, amount: 20, unit: "ml", conversionId: "orange-liqueur-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "lemon", grams: 20, amount: 20, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "ice", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [0, 1, 2], durationMs: 10000, params: { quantityG: 88 } },
      { op: "add", inputs: [3], durationMs: 5000, params: { quantityG: 80 } },
      { op: "mix", inputs: [], durationMs: 15000, params: { strength: 0.85 } },
      { op: "strain", inputs: [], durationMs: 10000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "bellini",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 150, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["italian"], mealRoleIds: ["drink"], servingContextIds: ["aperitif", "social-gathering"],
    flavor: { tastes: { sweet: 2 }, aromaIds: ["fruity", "floral"], textureIds: ["crisp"], characterIds: ["refreshing", "light"] },
    portions: [
      { id: "peach", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "prosecco", grams: 118.8, amount: 120, unit: "ml", conversionId: "prosecco:ml:weight-v1", role: "main", state: "liquid" },
      { id: "ice", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "peel", inputs: [0], durationMs: 30000 },
      { op: "blend", inputs: [0], durationMs: 30000, params: { strength: 0.7 }, targets: [{ dimension: "structural-integrity", maximum: 0.15, unit: "normalized" }] },
      { op: "chill", inputs: [], waitMs: 600000, params: { temperatureC: 4 } },
      { op: "add", inputs: [2], durationMs: 5000, params: { quantityG: 40 } },
      { op: "add", inputs: [0], durationMs: 8000, params: { quantityG: 100 } },
      { op: "add", inputs: [1], durationMs: 10000, params: { quantityG: 119 } },
      { op: "stir", inputs: [], durationMs: 8000, params: { strength: 0.25 }, targets: [{ dimension: "structural-integrity", minimum: 0.4, unit: "normalized" }] },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "amaretto-sour",
    itemType: "alcoholic-drink", servings: 1, yieldAmount: 120, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["bartending"], cuisineIds: ["italian"], mealRoleIds: ["drink"], servingContextIds: ["after-meal", "social-gathering"],
    flavor: { tastes: { sour: 3, sweet: 3 }, aromaIds: ["fruity"], textureIds: ["silky"], characterIds: ["refreshing", "comforting"] },
    portions: [
      { id: "amaretto-80", grams: 47.25, amount: 45, unit: "ml", conversionId: "amaretto-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "bourbon-80", grams: 14.1, amount: 15, unit: "ml", conversionId: "bourbon-80:ml:weight-v1", role: "main", state: "liquid" },
      { id: "lemon", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "simple-syrup", grams: 10, amount: 10, unit: "g", conversionId: "si:g:v1", role: "seasoning", state: "liquid", optional: true },
      { id: "egg", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared", optional: true },
      { id: "ice", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
    ],
    ops: [
      { op: "chill", inputs: [], waitMs: 300000, params: { temperatureC: -18 } },
      { op: "add", inputs: [0, 1, 2, 3, 4], durationMs: 10000, params: { quantityG: 131 } },
      { op: "add", inputs: [5], durationMs: 5000, params: { quantityG: 80 } },
      { op: "mix", inputs: [], durationMs: 18000, params: { strength: 0.9 }, targets: [{ dimension: "structural-integrity", minimum: 0.6, unit: "normalized" }] },
      { op: "strain", inputs: [], durationMs: 10000 },
      { op: "garnish", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
);


// ================= DESSERT (16) =================
drafts.push(
  {
    slug: "black-sesame-tangyuan",
    itemType: "dessert", servings: 4, yieldAmount: 16, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["chinese"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal"],
    flavor: { tastes: { sweet: 3 }, aromaIds: ["roasted"], textureIds: ["chewy", "soft"], characterIds: ["comforting", "warming"] },
    portions: [
      { id: "glutinous-rice-flour", grams: 200, amount: 200, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "drinking-water", grams: 160, amount: 160, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
      { id: "black-sesame-paste", grams: 120, amount: 120, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "powdered-sugar", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "usda-butter", grams: 20, amount: 20, unit: "g", conversionId: "si:g:v1", role: "main" },
    ],
    ops: [
      { op: "mix", inputs: [3, 2, 4], durationMs: 30000, params: { strength: 0.5 } },
      { op: "shape", inputs: [], durationMs: 30000 },
      { op: "chill", inputs: [], waitMs: 1800000, params: { temperatureC: 4 } },
      { op: "mix", inputs: [0, 1], durationMs: 120000, params: { strength: 0.6 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "shape", inputs: [2], durationMs: 300000, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "boil", inputs: [], waitMs: 480000, params: { temperatureC: 100 }, targets: [{ dimension: "doneness", minimum: 0.9, unit: "normalized" }], equipment: "saucepan" },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "red-bean-soup",
    itemType: "dessert", servings: 4, yieldAmount: 800, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["chinese"], mealRoleIds: ["dessert", "soup"], servingContextIds: ["after-meal"],
    flavor: { tastes: { sweet: 3 }, textureIds: ["brothy", "soft"], characterIds: ["comforting", "warming"] },
    portions: [
      { id: "red-bean-paste", grams: 250, amount: 250, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "drinking-water", grams: 800, amount: 800, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
      { id: "brown-sugar", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "dried-longan", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "add", inputs: [0, 1], durationMs: 30000, params: { quantityG: 1050 } },
      { op: "set-heat", durationMs: 30000, params: { temperatureC: 100 }, heat: { kind: "qualitative", descriptorId: "boil", sourceFactId: "" }, equipment: "saucepan" },
      { op: "simmer", inputs: [2, 3], waitMs: 2700000, params: { temperatureC: 95 }, targets: [{ dimension: "doneness", minimum: 0.9, unit: "normalized" }, { dimension: "wateriness", minimum: 0.6, maximum: 0.85, unit: "normalized" }], equipment: "saucepan" },
      { op: "stir", inputs: [], durationMs: 30000, params: { strength: 0.3 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "mango-pomelo-sago",
    itemType: "dessert", servings: 4, yieldAmount: 800, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["cantonese"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "afternoon-tea"],
    flavor: { tastes: { sweet: 3, sour: 1 }, aromaIds: ["fruity", "floral"], textureIds: ["creamy", "silky"], characterIds: ["refreshing", "comforting"] },
    portions: [
      { id: "mango", grams: 400, amount: 400, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "sago-pearls", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "coconut-milk", grams: 300, amount: 300, unit: "ml", conversionId: "coconut-milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "evaporated-milk", grams: 100, amount: 100, unit: "ml", conversionId: "evaporated-milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "granulated-sugar", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "boil", inputs: [1], waitMs: 1200000, params: { temperatureC: 100 }, targets: [{ dimension: "doneness", minimum: 0.9, unit: "normalized" }], equipment: "saucepan" },
      { op: "rinse", inputs: [], durationMs: 30000 },
      { op: "chill", inputs: [], waitMs: 1800000, params: { temperatureC: 4 } },
      { op: "dice", inputs: [0], durationMs: 60000, params: { cutSizeMm: 15, uniformity: 0.7 } },
      { op: "blend", inputs: [0, 3], durationMs: 30000, params: { strength: 0.6 }, targets: [{ dimension: "structural-integrity", maximum: 0.2, unit: "normalized" }] },
      { op: "mix", inputs: [2, 4], durationMs: 30000, params: { strength: 0.4 } },
      { op: "assemble", inputs: [1, 0], durationMs: 30000 },
      { op: "chill", inputs: [], waitMs: 3600000, params: { temperatureC: 4 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "hong-kong-milk-pudding",
    itemType: "dessert", servings: 4, yieldAmount: 4, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["cantonese"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "afternoon-tea"],
    flavor: { tastes: { sweet: 2 }, textureIds: ["silky", "soft"], characterIds: ["light", "comforting"] },
    portions: [
      { id: "milk", grams: 500, amount: 500, unit: "ml", conversionId: "milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "egg", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main", state: "prepared" },
      { id: "granulated-sugar", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "set-heat", durationMs: 120000, params: { temperatureC: 70 }, heat: { kind: "qualitative", descriptorId: "scald", sourceFactId: "" }, equipment: "saucepan" },
      { op: "add", inputs: [2], durationMs: 30000, params: { quantityG: 40 } },
      { op: "whisk", inputs: [1], durationMs: 30000, params: { strength: 0.3 } },
      { op: "mix", inputs: [], durationMs: 60000, params: { strength: 0.3 } },
      { op: "strain", inputs: [], durationMs: 15000 },
      { op: "steam", inputs: [], waitMs: 900000, params: { temperatureC: 85 }, targets: [{ dimension: "doneness", minimum: 0.9, unit: "normalized" }, { dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }], equipment: "steamer" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "chill", inputs: [], waitMs: 3600000, params: { temperatureC: 4 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "ginger-milk-curd",
    itemType: "dessert", servings: 2, yieldAmount: 2, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["chinese"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal"],
    flavor: { tastes: { sweet: 2, spicy: 1 }, aromaIds: ["gingery"], textureIds: ["silky", "soft"], characterIds: ["warming", "comforting"] },
    portions: [
      { id: "milk", grams: 400, amount: 400, unit: "ml", conversionId: "milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "ginger", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "granulated-sugar", grams: 20, amount: 20, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "grind", inputs: [1], durationMs: 30000, params: { cutSizeMm: 1, uniformity: 0.6 } },
      { op: "strain", inputs: [1], durationMs: 15000 },
      { op: "set-heat", durationMs: 180000, params: { temperatureC: 70 }, heat: { kind: "qualitative", descriptorId: "scald", sourceFactId: "" }, equipment: "saucepan" },
      { op: "add", inputs: [2], durationMs: 20000, params: { quantityG: 20 } },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "mix", inputs: [1], durationMs: 15000, params: { strength: 0.5 } },
      { op: "rest", inputs: [], waitMs: 600000, targets: [{ dimension: "structural-integrity", minimum: 0.8, unit: "normalized" }] },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "lotus-seed-goji-soup",
    itemType: "dessert", servings: 4, yieldAmount: 800, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["chinese"], mealRoleIds: ["dessert", "soup"], servingContextIds: ["after-meal"],
    flavor: { tastes: { sweet: 2 }, textureIds: ["brothy", "soft"], characterIds: ["comforting", "clean-tasting"] },
    portions: [
      { id: "lotus-seed", grams: 100, amount: 100, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "dried-longan", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "goji-berry", grams: 15, amount: 15, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "granulated-sugar", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "drinking-water", grams: 1000, amount: 1000, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
    ],
    ops: [
      { op: "rinse", inputs: [0, 1, 2], durationMs: 30000 },
      { op: "add", inputs: [0, 4], durationMs: 30000, params: { quantityG: 1100 } },
      { op: "set-heat", durationMs: 30000, params: { temperatureC: 100 }, heat: { kind: "qualitative", descriptorId: "boil", sourceFactId: "" }, equipment: "soup-pot" },
      { op: "simmer", inputs: [1], waitMs: 3600000, params: { temperatureC: 95 }, targets: [{ dimension: "doneness", minimum: 0.9, unit: "normalized" }], equipment: "soup-pot" },
      { op: "season", inputs: [2, 3], durationMs: 30000, params: { quantityG: 55 } },
      { op: "rest", inputs: [], waitMs: 300000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "tofu-pudding",
    itemType: "dessert", servings: 4, yieldAmount: 800, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["chinese"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "breakfast"],
    flavor: { tastes: { sweet: 2 }, textureIds: ["silky", "soft"], characterIds: ["light", "clean-tasting"] },
    portions: [
      { id: "soy-milk", grams: 800, amount: 800, unit: "ml", conversionId: "soy-milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "gelatin-powder", grams: 12, amount: 12, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "granulated-sugar", grams: 50, amount: 50, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "ginger", grams: 10, amount: 10, unit: "g", conversionId: "si:g:v1", role: "garnish", optional: true },
    ],
    ops: [
      { op: "set-heat", durationMs: 120000, params: { temperatureC: 80 }, heat: { kind: "qualitative", descriptorId: "scald", sourceFactId: "" }, equipment: "saucepan" },
      { op: "add", inputs: [1], durationMs: 30000, params: { quantityG: 12 } },
      { op: "stir", inputs: [2], durationMs: 30000, params: { strength: 0.4 } },
      { op: "strain", inputs: [], durationMs: 15000 },
      { op: "chill", inputs: [], waitMs: 10800000, params: { temperatureC: 4 }, targets: [{ dimension: "structural-integrity", minimum: 0.8, unit: "normalized" }] },
      { op: "garnish", inputs: [3], durationMs: 10000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "egg-waffles",
    itemType: "dessert", servings: 4, yieldAmount: 8, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["cantonese"], mealRoleIds: ["dessert"], servingContextIds: ["afternoon-tea", "social-gathering"],
    flavor: { tastes: { sweet: 3, salty: 1 }, aromaIds: ["toasty"], textureIds: ["crisp", "chewy"], characterIds: ["comforting", "light"] },
    portions: [
      { id: "wheat-flour", grams: 180, amount: 180, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "egg", grams: 100, amount: 2, unit: "piece", conversionId: "egg:piece:weight-v1", role: "main" },
      { id: "granulated-sugar", grams: 70, amount: 70, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "evaporated-milk", grams: 180, amount: 180, unit: "ml", conversionId: "evaporated-milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "drinking-water", grams: 70, amount: 70, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
      { id: "usda-butter", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "usda-vanilla", grams: 4, amount: 4, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "whisk", inputs: [1, 2], durationMs: 60000, params: { strength: 0.5 } },
      { op: "add", inputs: [3, 4, 6], durationMs: 20000, params: { quantityG: 254 } },
      { op: "add", inputs: [0], durationMs: 20000, params: { quantityG: 180 } },
      { op: "mix", inputs: [5], durationMs: 60000, params: { strength: 0.4 }, targets: [{ dimension: "structural-integrity", minimum: 0.6, unit: "normalized" }] },
      { op: "rest", inputs: [], waitMs: 1800000 },
      { op: "set-heat", durationMs: 180000, params: { temperatureC: 200 }, heat: { kind: "qualitative", descriptorId: "pan-hot", sourceFactId: "" }, equipment: "frying-pan" },
      { op: "pan-fry", inputs: [], durationMs: 240000, params: { temperatureC: 190 }, targets: [{ dimension: "browning", minimum: 0.5, maximum: 0.75, unit: "normalized" }, { dimension: "doneness", minimum: 0.95, unit: "normalized" }], equipment: "frying-pan" },
      { op: "remove", inputs: [], durationMs: 5000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "sago-coconut-dessert",
    itemType: "dessert", servings: 4, yieldAmount: 600, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["thai"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "afternoon-tea"],
    flavor: { tastes: { sweet: 3 }, aromaIds: ["floral", "fruity"], textureIds: ["creamy", "chewy"], characterIds: ["refreshing", "comforting"] },
    portions: [
      { id: "sago-pearls", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "coconut-milk", grams: 400, amount: 400, unit: "ml", conversionId: "coconut-milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "granulated-sugar", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "mango", grams: 200, amount: 200, unit: "g", conversionId: "si:g:v1", role: "main" },
    ],
    ops: [
      { op: "boil", inputs: [0], waitMs: 1200000, params: { temperatureC: 100 }, targets: [{ dimension: "doneness", minimum: 0.9, unit: "normalized" }], equipment: "saucepan" },
      { op: "rinse", inputs: [], durationMs: 30000 },
      { op: "mix", inputs: [1, 2], durationMs: 30000, params: { strength: 0.4 } },
      { op: "set-heat", durationMs: 60000, params: { temperatureC: 80 }, heat: { kind: "qualitative", descriptorId: "scald", sourceFactId: "" }, equipment: "saucepan" },
      { op: "dice", inputs: [3], durationMs: 60000, params: { cutSizeMm: 15, uniformity: 0.7 } },
      { op: "assemble", inputs: [0, 3], durationMs: 30000 },
      { op: "chill", inputs: [], waitMs: 3600000, params: { temperatureC: 4 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "coconut-jelly",
    itemType: "dessert", servings: 6, yieldAmount: 6, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["thai"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "afternoon-tea"],
    flavor: { tastes: { sweet: 3 }, aromaIds: ["floral"], textureIds: ["silky", "soft"], characterIds: ["refreshing", "light"] },
    portions: [
      { id: "coconut-milk", grams: 400, amount: 400, unit: "ml", conversionId: "coconut-milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "drinking-water", grams: 200, amount: 200, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
      { id: "gelatin-powder", grams: 15, amount: 15, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "granulated-sugar", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "add", inputs: [1, 3], durationMs: 30000, params: { quantityG: 260 } },
      { op: "set-heat", durationMs: 120000, params: { temperatureC: 80 }, heat: { kind: "qualitative", descriptorId: "scald", sourceFactId: "" }, equipment: "saucepan" },
      { op: "add", inputs: [2], durationMs: 30000, params: { quantityG: 15 } },
      { op: "mix", inputs: [0], durationMs: 30000, params: { strength: 0.4 } },
      { op: "strain", inputs: [], durationMs: 15000 },
      { op: "chill", inputs: [], waitMs: 14400000, params: { temperatureC: 4 }, targets: [{ dimension: "structural-integrity", minimum: 0.85, unit: "normalized" }] },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "osmanthus-cake",
    itemType: "dessert", servings: 6, yieldAmount: 6, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["chinese"], mealRoleIds: ["dessert"], servingContextIds: ["afternoon-tea", "after-meal"],
    flavor: { tastes: { sweet: 2 }, aromaIds: ["floral"], textureIds: ["silky", "soft"], characterIds: ["light", "refreshing"] },
    portions: [
      { id: "drinking-water", grams: 500, amount: 500, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
      { id: "osmanthus-dried", grams: 10, amount: 10, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "gelatin-powder", grams: 20, amount: 20, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "granulated-sugar", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "brew", inputs: [1], waitMs: 600000, params: { temperatureC: 90 }, targets: [{ dimension: "aroma", minimum: 0.6, unit: "normalized" }], equipment: "teapot" },
      { op: "strain", inputs: [], durationMs: 15000 },
      { op: "add", inputs: [2, 3], durationMs: 30000, params: { quantityG: 60 } },
      { op: "mix", inputs: [], durationMs: 30000, params: { strength: 0.4 } },
      { op: "chill", inputs: [], waitMs: 10800000, params: { temperatureC: 4 }, targets: [{ dimension: "structural-integrity", minimum: 0.8, unit: "normalized" }] },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "lvdagun",
    itemType: "dessert", servings: 8, yieldAmount: 8, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["chinese"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "afternoon-tea"],
    flavor: { tastes: { sweet: 3 }, aromaIds: ["roasted", "toasty"], textureIds: ["chewy", "soft"], characterIds: ["comforting", "hearty"] },
    portions: [
      { id: "glutinous-rice-flour", grams: 250, amount: 250, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "drinking-water", grams: 200, amount: 200, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
      { id: "red-bean-paste", grams: 200, amount: 200, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "roasted-peanut", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "soy-milk", grams: 50, amount: 50, unit: "ml", conversionId: "soy-milk:ml:weight-v1", role: "seasoning", state: "liquid", optional: true },
    ],
    ops: [
      { op: "crush", inputs: [3], durationMs: 30000, params: { strength: 0.7 } },
      { op: "mix", inputs: [0, 1, 4], durationMs: 120000, params: { strength: 0.6 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "steam", inputs: [], waitMs: 1500000, params: { temperatureC: 100 }, targets: [{ dimension: "doneness", minimum: 0.95, unit: "normalized" }], equipment: "steamer" },
      { op: "shape", inputs: [2], durationMs: 300000, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "season", inputs: [3], durationMs: 30000, params: { quantityG: 60 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "tang-bu-shuai",
    itemType: "dessert", servings: 8, yieldAmount: 16, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["chinese"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "social-gathering"],
    flavor: { tastes: { sweet: 4 }, aromaIds: ["roasted"], textureIds: ["chewy", "soft"], characterIds: ["comforting", "warming"] },
    portions: [
      { id: "glutinous-rice-flour", grams: 200, amount: 200, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "drinking-water", grams: 160, amount: 160, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
      { id: "brown-sugar", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "roasted-peanut", grams: 80, amount: 80, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "ginger", grams: 10, amount: 10, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "crush", inputs: [3], durationMs: 30000, params: { strength: 0.6 } },
      { op: "mix", inputs: [0, 1], durationMs: 120000, params: { strength: 0.6 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "shape", inputs: [], durationMs: 300000, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "boil", inputs: [], waitMs: 480000, params: { temperatureC: 100 }, targets: [{ dimension: "doneness", minimum: 0.9, unit: "normalized" }], equipment: "saucepan" },
      { op: "simmer", inputs: [2, 4], waitMs: 600000, params: { temperatureC: 95 }, targets: [{ dimension: "sweet", minimum: 0.7, unit: "normalized" }], equipment: "saucepan" },
      { op: "season", inputs: [3], durationMs: 30000, params: { quantityG: 80 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "nuomici",
    itemType: "dessert", servings: 8, yieldAmount: 8, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["chinese"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "afternoon-tea"],
    flavor: { tastes: { sweet: 3 }, aromaIds: ["fruity"], textureIds: ["chewy", "soft"], characterIds: ["refreshing", "comforting"] },
    portions: [
      { id: "glutinous-rice-flour", grams: 250, amount: 250, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "drinking-water", grams: 220, amount: 220, unit: "ml", conversionId: "drinking-water:ml:weight-v1", role: "main", state: "liquid" },
      { id: "mango", grams: 300, amount: 300, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "coconut-milk", grams: 100, amount: 100, unit: "ml", conversionId: "coconut-milk:ml:weight-v1", role: "seasoning", state: "liquid" },
      { id: "powdered-sugar", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "mix", inputs: [0, 1], durationMs: 120000, params: { strength: 0.6 }, targets: [{ dimension: "structural-integrity", minimum: 0.7, unit: "normalized" }] },
      { op: "steam", inputs: [], waitMs: 1500000, params: { temperatureC: 100 }, targets: [{ dimension: "doneness", minimum: 0.95, unit: "normalized" }], equipment: "steamer" },
      { op: "chill", inputs: [], waitMs: 1800000, params: { temperatureC: 20 } },
      { op: "dice", inputs: [2], durationMs: 60000, params: { cutSizeMm: 20, uniformity: 0.7 } },
      { op: "shape", inputs: [2], durationMs: 300000, targets: [{ dimension: "structural-integrity", minimum: 0.75, unit: "normalized" }] },
      { op: "season", inputs: [3, 4], durationMs: 30000, params: { quantityG: 130 } },
      { op: "chill", inputs: [], waitMs: 1800000, params: { temperatureC: 4 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "greek-yogurt-honey",
    itemType: "dessert", servings: 2, yieldAmount: 2, yieldUnit: "piece",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["greek"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "breakfast"],
    flavor: { tastes: { sour: 2, sweet: 2 }, textureIds: ["creamy"], characterIds: ["light", "refreshing"] },
    portions: [
      { id: "usda-yogurt", grams: 400, amount: 400, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "usda-honey", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
      { id: "walnut", grams: 30, amount: 30, unit: "g", conversionId: "si:g:v1", role: "garnish" },
    ],
    ops: [
      { op: "chill", inputs: [0], waitMs: 3600000, params: { temperatureC: 4 } },
      { op: "crush", inputs: [2], durationMs: 15000, params: { strength: 0.5 } },
      { op: "assemble", inputs: [], durationMs: 30000 },
      { op: "season", inputs: [1], durationMs: 10000, params: { quantityG: 30 }, targets: [{ dimension: "sweet", minimum: 0.6, unit: "normalized" }] },
      { op: "garnish", inputs: [2], durationMs: 10000 },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
  {
    slug: "taro-coconut-dessert",
    itemType: "dessert", servings: 4, yieldAmount: 700, yieldUnit: "ml",
    simulationProfile: "requires-cat-kitchen-v2",
    categoryTags: ["dessert"], cuisineIds: ["chinese"], mealRoleIds: ["dessert"], servingContextIds: ["after-meal", "afternoon-tea"],
    flavor: { tastes: { sweet: 3 }, textureIds: ["creamy", "soft"], characterIds: ["comforting", "warming"] },
    portions: [
      { id: "taro", grams: 400, amount: 400, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "coconut-milk", grams: 400, amount: 400, unit: "ml", conversionId: "coconut-milk:ml:weight-v1", role: "main", state: "liquid" },
      { id: "sago-pearls", grams: 40, amount: 40, unit: "g", conversionId: "si:g:v1", role: "main" },
      { id: "granulated-sugar", grams: 60, amount: 60, unit: "g", conversionId: "si:g:v1", role: "seasoning" },
    ],
    ops: [
      { op: "peel", inputs: [0], durationMs: 60000 },
      { op: "dice", inputs: [0], durationMs: 60000, params: { cutSizeMm: 20, uniformity: 0.7 } },
      { op: "boil", inputs: [2], waitMs: 1200000, params: { temperatureC: 100 }, targets: [{ dimension: "doneness", minimum: 0.9, unit: "normalized" }], equipment: "saucepan" },
      { op: "steam", inputs: [0], waitMs: 1200000, params: { temperatureC: 100 }, targets: [{ dimension: "doneness", minimum: 0.95, unit: "normalized" }], equipment: "steamer" },
      { op: "add", inputs: [1, 3], durationMs: 30000, params: { quantityG: 460 } },
      { op: "simmer", inputs: [0], waitMs: 600000, params: { temperatureC: 95 }, targets: [{ dimension: "doneness", minimum: 0.85, unit: "normalized" }, { dimension: "structural-integrity", maximum: 0.4, unit: "normalized" }], equipment: "saucepan" },
      { op: "chill", inputs: [], waitMs: 3600000, params: { temperatureC: 4 } },
      { op: "serve", inputs: [], durationMs: 5000 },
    ],
  },
);

const count = writeRecipes(drafts, options);
process.stdout.write(`Generated ${count} batch-B recipes\n`);
